workflows:
  ios-workflow:
    name: iOS Workflow
    max_build_duration: 120
    instance_type: mac_mini_m1
    environment:
      groups:
        - app_store_credentials
      flutter: stable
      xcode: latest
      cocoapods: default
    scripts:
      - name: Get Flutter dependencies
        script: |
          flutter pub get
      - name: Verify scheme exists
        script: |
          if [ -f "ios/Runner.xcodeproj/xcshareddata/xcschemes/Runner.xcscheme" ]; then
            echo "✅ Scheme file found"
          else
            echo "❌ Scheme file not found"
            exit 1
          fi
      - name: Install CocoaPods dependencies
        script: |
          cd ios
          pod install
          cd ..
      - name: Build iOS IPA
        script: |
          flutter build ipa --release
    artifacts:
      - build/ios/ipa/*.ipa
    publishing:
      email:
        recipients:
          - mhanytalaat@icloud.com
        notify:
          success: true
          failure: true
