# This file is kept minimal to allow Workflow Editor to take precedence
# Configure iOS builds using Codemagic Workflow Editor UI instead
# Code signing and App Store Connect should be configured in Workflow Editor UI
#
# TO FIX BUILD NUMBER CACHING:
# Add the script from CODEMAGIC_BUILD_NUMBER_FIX.md as a PRE-BUILD script
# in Codemagic UI → Default Workflow → Edit → Build → Pre-build script
#
workflows:
  ios-workflow:
    name: iOS Workflow
  
  android-workflow:
    name: Android Workflow
    max_build_duration: 120
    instance_type: mac_mini_m1
    environment:
      groups:
        - keystore_credentials
      flutter: stable
    scripts:
      - name: Clean build
        script: |
          flutter clean
          # Remove Android build cache
          rm -rf build/app
          rm -rf .dart_tool
      - name: Get Flutter dependencies
        script: |
          flutter pub get
      - name: Set up Android signing
        script: |
          # Create key.properties file from environment variables
          # Codemagic automatically provides these when keystore is uploaded to keystore_credentials group
          cat > android/key.properties << EOF
          storePassword=$CM_KEYSTORE_PASSWORD
          keyPassword=$CM_KEY_PASSWORD
          keyAlias=$CM_KEY_ALIAS
          EOF
          
          # Copy keystore file if provided as environment variable
          if [ -n "$CM_KEYSTORE_PATH" ]; then
            cp "$CM_KEYSTORE_PATH" android/padelcore-keystore.jks
          elif [ -f "$CM_KEYSTORE" ]; then
            cp "$CM_KEYSTORE" android/padelcore-keystore.jks
          fi
          
          # Verify keystore file exists
          if [ ! -f "android/padelcore-keystore.jks" ]; then
            echo "ERROR: Keystore file not found!"
            echo "Please ensure padelcore-keystore.jks is uploaded to keystore_credentials group in Codemagic"
            exit 1
          fi
          
          # Verify key.properties exists
          if [ ! -f "android/key.properties" ]; then
            echo "ERROR: key.properties not created!"
            exit 1
          fi
          
          echo "Keystore setup complete"
      - name: Build Android App Bundle (Release)
        script: |
          flutter build appbundle --release
    artifacts:
      - build/app/outputs/bundle/release/*.aab
    publishing:
      email:
        recipients:
          - mhanytalaat@icloud.com
        notify:
          success: true
          failure: true
