workflows:
  ios-workflow:
    name: iOS Workflow
    max_build_duration: 120
    instance_type: mac_mini_m1
    environment:
      flutter: stable
      xcode: latest
      cocoapods: default
      # Configure Xcode project for automatic code signing
      xcode-project:
        ios:
          # Codemagic will automatically use certificates from your account
          # Make sure certificate and provisioning profile are in Codemagic Settings
          bundle_id: com.padelcore.app
      vars:
        APP_STORE_ID: your_app_store_id
        BUNDLE_ID: com.padelcore.app
        # API key content for App Store Connect publishing
        APP_STORE_CONNECT_API_KEY_CONTENT: |
          -----BEGIN PRIVATE KEY-----
          MIGTAgEAMBMGByqGSM49AgEGCCqGSM49AwEHBHkwdwIBAQQg3yFkktNRxOD6kBlh
          9HtNcvWXJjFFc47njCkXpsObqmCgCgYIKoZIzj0DAQehRANCAAQVg4LwAK/w4Vxf
          BRcXdQKEq0O9bd108qfTrjxcAWPyOmEjY3dTeeQfj0wurgGcpwB4mh4+fRVG44+B
          MT++yulg
          -----END PRIVATE KEY-----
    scripts:
      - name: Get Flutter dependencies
        script: |
          flutter pub get
      - name: Verify scheme exists
        script: |
          if [ -f "ios/Runner.xcodeproj/xcshareddata/xcschemes/Runner.xcscheme" ]; then
            echo "✅ Scheme file found"
          else
            echo "❌ Scheme file not found"
            exit 1
          fi
      - name: Install CocoaPods dependencies
        script: |
          cd ios
          pod install
          cd ..
      - name: Set up App Store Connect API key
        script: |
          # Write API key to file
          mkdir -p ~/.appstoreconnect/private_keys
          echo "$APP_STORE_CONNECT_API_KEY_CONTENT" > ~/.appstoreconnect/private_keys/AuthKey_V8Z6S6JJKJ.p8
          chmod 600 ~/.appstoreconnect/private_keys/AuthKey_V8Z6S6JJKJ.p8
          echo "✅ API key file created"
      - name: Fetch and install certificates using Codemagic CLI
        script: |
          # Codemagic should automatically fetch certificates when app_store_connect is configured
          # But if it doesn't, we'll rely on the certificates already in Codemagic account
          echo "Checking for available certificates..."
          # The certificates should be automatically available from Codemagic's code signing setup
      - name: Build iOS IPA (Release)
        script: |
          flutter build ipa --release
    artifacts:
      - build/ios/ipa/*.ipa
    publishing:
      app_store_connect:
        # App Store Connect API key for automatic certificate management
        # Codemagic will automatically fetch and use certificates when this is configured
        # The API key file is created in the script above
        api_key: $APP_STORE_CONNECT_API_KEY_CONTENT
        key_id: V8Z6S6JJKJ
        issuer_id: c34d1e02-e3e4-4ef1-baf1-0fe68633fc22
        submit_to_testflight: true
      email:
        recipients:
          - mhanytalaat@icloud.com
        notify:
          success: true
          failure: true
  
  android-workflow:
    name: Android Workflow
    max_build_duration: 120
    instance_type: mac_mini_m1
    environment:
      groups:
        - keystore_credentials
      flutter: stable
    scripts:
      - name: Get Flutter dependencies
        script: |
          flutter pub get
      - name: Build Android App Bundle (Release)
        script: |
          flutter build appbundle --release
    artifacts:
      - build/app/outputs/bundle/release/*.aab
    publishing:
      email:
        recipients:
          - mhanytalaat@icloud.com
        notify:
          success: true
          failure: true