workflows:
  ios-workflow:
    name: iOS Workflow
    max_build_duration: 120
    instance_type: mac_mini_m1
    environment:
      flutter: stable
      xcode: latest
      cocoapods: default
      vars:
        APP_STORE_ID: your_app_store_id
        BUNDLE_ID: com.padelcore.app
    scripts:
      - name: Get Flutter dependencies
        script: |
          flutter pub get
      - name: Verify scheme exists
        script: |
          if [ -f "ios/Runner.xcodeproj/xcshareddata/xcschemes/Runner.xcscheme" ]; then
            echo "✅ Scheme file found"
          else
            echo "❌ Scheme file not found"
            exit 1
          fi
      - name: Install CocoaPods dependencies
        script: |
          cd ios
          pod install
          cd ..
      - name: Build iOS IPA (Release)
        script: |
          flutter build ipa --release
    artifacts:
      - build/ios/ipa/*.ipa
    publishing:
      app_store_connect:
        # App Store Connect API key for automatic certificate management
        # This will automatically fetch and use certificates during build
        api_key: Encrypted\ API\ Key\ File  # Upload your .p8 file in Codemagic Settings → Code signing → App Store Connect API keys
        key_id: 8HRJ2UHKD3
        issuer_id: c34d1e02-e3e4-4ef1-baf1-0fe68633fc22
        submit_to_testflight: true
      email:
        recipients:
          - mhanytalaat@icloud.com
        notify:
          success: true
          failure: true
  
  android-workflow:
    name: Android Workflow
    max_build_duration: 120
    instance_type: mac_mini_m1
    environment:
      groups:
        - keystore_credentials
      flutter: stable
    scripts:
      - name: Get Flutter dependencies
        script: |
          flutter pub get
      - name: Build Android App Bundle (Release)
        script: |
          flutter build appbundle --release
    artifacts:
      - build/app/outputs/bundle/release/*.aab
    publishing:
      email:
        recipients:
          - mhanytalaat@icloud.com
        notify:
          success: true
          failure: true