# This file is kept minimal to allow Workflow Editor to take precedence
# Configure iOS builds using Codemagic Workflow Editor UI instead
# Code signing and App Store Connect should be configured in Workflow Editor UI
#
# Spark: "Set Spark API dart-defines (iOS)" exports FLUTTER_DART_DEFINES from SPARK_API_KEY.
# Your iOS build step (in Workflow Editor) must pass it: flutter build ipa $FLUTTER_DART_DEFINES
# (or add "Additional build arguments": $FLUTTER_DART_DEFINES). Otherwise Spark sync is disabled in the app.
#
# Version is read from pubspec.yaml (e.g. 1.1.39+87). Sync script below ensures
# iOS Generated.xcconfig gets the same build number so Codemagic doesn't use a cached one.
#
workflows:
  ios-workflow:
    name: iOS Workflow
    environment:
      flutter: stable
    scripts:
      - name: Sync version from pubspec (iOS)
        script: |
          set -e
          VERSION=$(grep "version:" pubspec.yaml | sed 's/version: //' | tr -d ' ')
          VERSION_NAME=$(echo $VERSION | cut -d'+' -f1)
          BUILD_NUMBER=$(echo $VERSION | cut -d'+' -f2)
          echo "Version: $VERSION_NAME Build: $BUILD_NUMBER"
          rm -f ios/Flutter/Generated.xcconfig
          mkdir -p ios/Flutter
          cat > ios/Flutter/Generated.xcconfig << EOF
          FLUTTER_ROOT=\$(PROJECT_DIR)/../Flutter
          FLUTTER_APPLICATION_PATH=\$(PROJECT_DIR)/..
          FLUTTER_TARGET=lib/main.dart
          FLUTTER_BUILD_DIR=build
          SYMROOT=\$(SOURCE_ROOT)/../build/ios
          FLUTTER_BUILD_NAME=$VERSION_NAME
          FLUTTER_BUILD_NUMBER=$BUILD_NUMBER
          EOF
          cat ios/Flutter/Generated.xcconfig
      - name: Set Spark API dart-defines (iOS)
        script: |
          if [ -n "${SPARK_API_KEY:-}" ]; then
            export FLUTTER_DART_DEFINES="--dart-define=SPARK_API_KEY=$SPARK_API_KEY"
            [ -n "${SPARK_BASE_URL:-}" ] && export FLUTTER_DART_DEFINES="$FLUTTER_DART_DEFINES --dart-define=SPARK_BASE_URL=$SPARK_BASE_URL"
            echo "SPARK_API_KEY is set - Spark sync will be enabled in build"
          else
            export FLUTTER_DART_DEFINES=""
            echo "SPARK_API_KEY not set - Spark sync will be disabled in app"
          fi
          echo "FLUTTER_DART_DEFINES=$FLUTTER_DART_DEFINES"
      - name: Get Flutter dependencies
        script: |
          flutter pub get
  
  android-workflow:
    name: Android Workflow
    max_build_duration: 120
    instance_type: mac_mini_m1
    environment:
      groups:
        - keystore_credentials
      flutter: stable
    scripts:
      - name: Sync version from pubspec (Android)
        script: |
          set -e
          VERSION=$(grep "version:" pubspec.yaml | sed 's/version: //' | tr -d ' ')
          VERSION_NAME=$(echo $VERSION | cut -d'+' -f1)
          BUILD_NUMBER=$(echo $VERSION | cut -d'+' -f2)
          echo "Version: $VERSION_NAME Build: $BUILD_NUMBER"
      - name: Set Spark API dart-defines (Android)
        script: |
          if [ -n "${SPARK_API_KEY:-}" ]; then
            export FLUTTER_DART_DEFINES="--dart-define=SPARK_API_KEY=$SPARK_API_KEY"
            [ -n "${SPARK_BASE_URL:-}" ] && export FLUTTER_DART_DEFINES="$FLUTTER_DART_DEFINES --dart-define=SPARK_BASE_URL=$SPARK_BASE_URL"
            echo "SPARK_API_KEY is set - Spark sync will be enabled in build"
          else
            export FLUTTER_DART_DEFINES=""
            echo "SPARK_API_KEY not set - Spark sync will be disabled in app"
          fi
          echo "FLUTTER_DART_DEFINES=$FLUTTER_DART_DEFINES"
      - name: Clean build
        script: |
          flutter clean
          # Remove Android build cache
          rm -rf build/app
          rm -rf .dart_tool
      - name: Get Flutter dependencies
        script: |
          flutter pub get
      - name: Set up Android signing
        script: |
          # Create key.properties file from environment variables
          # Codemagic automatically provides these when keystore is uploaded to keystore_credentials group
          cat > android/key.properties << EOF
          storePassword=$CM_KEYSTORE_PASSWORD
          keyPassword=$CM_KEY_PASSWORD
          keyAlias=$CM_KEY_ALIAS
          EOF
          
          # Copy keystore file if provided as environment variable
          if [ -n "$CM_KEYSTORE_PATH" ]; then
            cp "$CM_KEYSTORE_PATH" android/padelcore-keystore.jks
          elif [ -f "$CM_KEYSTORE" ]; then
            cp "$CM_KEYSTORE" android/padelcore-keystore.jks
          fi
          
          # Verify keystore file exists
          if [ ! -f "android/padelcore-keystore.jks" ]; then
            echo "ERROR: Keystore file not found!"
            echo "Please ensure padelcore-keystore.jks is uploaded to keystore_credentials group in Codemagic"
            exit 1
          fi
          
          # Verify key.properties exists
          if [ ! -f "android/key.properties" ]; then
            echo "ERROR: key.properties not created!"
            exit 1
          fi
          
          echo "Keystore setup complete"
      - name: Build Android App Bundle (Release)
        script: |
          flutter build appbundle --release $FLUTTER_DART_DEFINES
    artifacts:
      - build/app/outputs/bundle/release/*.aab
    publishing:
      email:
        recipients:
          - mhanytalaat@icloud.com
        notify:
          success: true
          failure: true
