// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCvLlo-pzE1JQn73CRsndF0EJ39fApAt-w',
    appId: '1:1087756281644:web:11b4082aac7fa3ad53ae89',
    messagingSenderId: '1087756281644',
    projectId: 'padelcore-app',
    authDomain: 'padelcore-app.firebaseapp.com',
    storageBucket: 'padelcore-app.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC59LhvQ9mmD7ByUq_3Vx0OaDsdwXaQvmg',
    appId: '1:1087756281644:android:eabe2f91dc35560f53ae89',
    messagingSenderId: '1087756281644',
    projectId: 'padelcore-app',
    storageBucket: 'padelcore-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBQs-TR9NzB1XDUOpCoyvLgzF_c6ukz9_s',
    appId: '1:1087756281644:ios:ab581a1a0a90a43053ae89',
    messagingSenderId: '1087756281644',
    projectId: 'padelcore-app',
    storageBucket: 'padelcore-app.firebasestorage.app',
    iosBundleId: 'com.padelcore.app',
  );
}
