// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        return linux;
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCvLlo-pzE1JQn73CRsndF0EJ39fApAt-w',
    appId: '1:1087756281644:web:11b4082aac7fa3ad53ae89',
    messagingSenderId: '1087756281644',
    projectId: 'padelcore-app',
    authDomain: 'padelcore-app.firebaseapp.com',
    storageBucket: 'padelcore-app.firebasestorage.app',
    measurementId: 'G-3TD52WMYV6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC59LhvQ9mmD7ByUq_3Vx0OaDsdwXaQvmg',
    appId: '1:1087756281644:android:eabe2f91dc35560f53ae89',
    messagingSenderId: '1087756281644',
    projectId: 'padelcore-app',
    storageBucket: 'padelcore-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBQs-TR9NzB1XDUOpCoyvLgzF_c6ukz9_s',
    appId: '1:1087756281644:ios:ab581a1a0a90a43053ae89',
    messagingSenderId: '1087756281644',
    projectId: 'padelcore-app',
    storageBucket: 'padelcore-app.firebasestorage.app',
    androidClientId: '1087756281644-e45ukdc9ed3uriji2n8tmv2pifug1d49.apps.googleusercontent.com',
    iosClientId: '1087756281644-vl94gi1rgb38c7ui4uu728rorkh9dqlo.apps.googleusercontent.com',
    iosBundleId: 'com.padelcore.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBQs-TR9NzB1XDUOpCoyvLgzF_c6ukz9_s',
    appId: '1:1087756281644:ios:4ade3cd94baf500c53ae89',
    messagingSenderId: '1087756281644',
    projectId: 'padelcore-app',
    storageBucket: 'padelcore-app.firebasestorage.app',
    androidClientId: '1087756281644-e45ukdc9ed3uriji2n8tmv2pifug1d49.apps.googleusercontent.com',
    iosClientId: '1087756281644-drudrpffibbpjjiffqsofc2nisd6sq2e.apps.googleusercontent.com',
    iosBundleId: 'com.example.padelBooking',
  );

  /// Desktop platforms use the same project as web (padelcore-app).

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBsCM_G9em9rvPMlsXD4wKQvfhejVdeuR0',
    appId: '1:1087756281644:web:318f0743f8ee249953ae89',
    messagingSenderId: '1087756281644',
    projectId: 'padelcore-app',
    authDomain: 'padelcore-app.firebaseapp.com',
    storageBucket: 'padelcore-app.firebasestorage.app',
    measurementId: 'G-L3B979NWCT',
  );

  static const FirebaseOptions linux = FirebaseOptions(
    apiKey: 'AIzaSyCvLlo-pzE1JQn73CRsndF0EJ39fApAt-w',
    appId: '1:1087756281644:web:11b4082aac7fa3ad53ae89',
    messagingSenderId: '1087756281644',
    projectId: 'padelcore-app',
    authDomain: 'padelcore-app.firebaseapp.com',
    storageBucket: 'padelcore-app.firebasestorage.app',
  );
}